# Generated by Django 4.2.17 on 2025-01-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_item_description_alter_item_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="nutritional_value",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
