# Generated by Django 4.2.17 on 2025-01-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_item_nutritional_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="spoonacular_id",
            field=models.IntegerField(null=True),
        ),
    ]
