# Generated by Django 4.2.17 on 2025-01-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_remove_cart_items_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="items",
            field=models.ManyToManyField(through="orders.CartItem", to="orders.item"),
        ),
    ]
