# Generated by Django 4.2.17 on 2025-01-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0009_cart_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
